In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import(
    mean_absolute_error,#Average prediction mistake made by the model...actual-predicted
    mean_squared_error,#Average squared mistake made by the model.....To punish large mistakes more heavily...10² = 100
    r2_score#How much of the data pattern the model understands.
)

#Lower MAE,mse = Better Model
#r2 higher= better value
#range
#1.0  = Perfect
#0.9  = Excellent
#0.8  = Very Good
#0.7  = Good
#0.5  = Average
#0    = No Learning
#<0   = Very Bad Model

In [ ]:

#loading the data
#to study the data for any information
df=pd.read_csv("file.csv\Regression_Dataset_1000.csv")
df

     Study_Hours  Attendance  Assignments_Completed  Exam_Score
0            6.8        51.3                      9       62.29
1            2.3        55.1                     18       55.77
2            4.8        51.5                      7       48.10
3            6.4        78.1                     18       89.82
4            5.0        63.9                      1       51.35
..           ...         ...                    ...         ...
995          1.1        93.7                      5       36.07
996          1.0        79.8                     18       65.89
997          1.8        60.5                     12       45.38
998          9.2        92.6                      5       77.00
999          3.0        91.7                      7       48.80

[1000 rows x 4 columns]

In [26]:
df.head(5)

   Study_Hours  Attendance  Assignments_Completed  Exam_Score
0          6.8        51.3                      9       62.29
1          2.3        55.1                     18       55.77
2          4.8        51.5                      7       48.10
3          6.4        78.1                     18       89.82
4          5.0        63.9                      1       51.35

In [ ]:
#features and target
x=df[
        "Study_Hours",
        "Attendance",
        "Assignments_Completed"
]
y=df["Exam_Score"]

In [28]:
print (x)

     Study_Hours  Attendance  Assignments_Completed
0            6.8        51.3                      9
1            2.3        55.1                     18
2            4.8        51.5                      7
3            6.4        78.1                     18
4            5.0        63.9                      1
..           ...         ...                    ...
995          1.1        93.7                      5
996          1.0        79.8                     18
997          1.8        60.5                     12
998          9.2        92.6                      5
999          3.0        91.7                      7

[1000 rows x 3 columns]

In [29]:
print (y)

0      62.29
1      55.77
2      48.10
3      89.82
4      51.35
       ...
995    36.07
996    65.89
997    45.38
998    77.00
999    48.80
Name: Exam_Score, Length: 1000, dtype: float64

In [30]:
#train and split
x_train,x_test,y_train,y_test=train_test_split(# ek set for train and ek set for testing
    x,
    y,
    test_size=0.20, #for splitting in 20 /80 ...if we want 70/30 theh size will be 0.30
    random_state=42 #after prediction it compares with the actual data
)#computational value where we randomly select the data for splitting without any vedbhav diffferentiation

In [31]:
#model training
model=LinearRegression()
model.fit(
    x_train,
    y_train
)

LinearRegression()

In [32]:
#prediction
y_pred=model.predict(x_test)

In [ ]:
#evaluation
mae=mean_absolute_error(
    y_test,
    y_pred
)
mse=mean_squared_error(
    y_test,
    y_pred
)

rmse=np.sqrt(mse)#The value becomes too large and is no longer in the original unit,So we take the square root:Now the error is back in the original unit.

r2=r2_score(
    y_test,
    y_pred
)

print("\nMAE=",mae)
print("MSE=",mse)
print("RMSE=",rmse)
print("R2 Score=",r2)

MAE= 4.858862511564996
MSE= 32.067567224731484
RMSE= 5.66282325565009
R2 Score= 0.9095475926512209

In [ ]:
#actual vs predicted
results = pd.DataFrame({#used to create table
    "Actual": y_test,
    "Predicted": y_pred
})

print(results.head())

     Actual  Predicted
521   30.57  38.004657
737   76.98  72.907285
740   55.49  62.583274
660   81.46  74.247568
411   94.86  88.130682