In [127]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
df=pd.read_csv("file.csv/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [128]:
print(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [129]:
print(df.tail())

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [130]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [131]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [132]:
df.describe().round(1)

          age     bmi  children  charges
count  1338.0  1338.0    1338.0   1338.0
mean     39.2    30.7       1.1  13270.4
std      14.0     6.1       1.2  12110.0
min      18.0    16.0       0.0   1121.9
25%      27.0    26.3       0.0   4740.3
50%      39.0    30.4       1.0   9382.0
75%      51.0    34.7       2.0  16639.9
max      64.0    53.1       5.0  63770.4

In [133]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [134]:
df.isnull().mean()*100

age         0.0
sex         0.0
bmi         0.0
children    0.0
smoker      0.0
region      0.0
charges     0.0
dtype: float64

In [135]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [136]:
df["age"].value_counts()

age
18    69
19    68
46    29
52    29
50    29
47    29
48    29
51    29
45    29
20    29
24    28
27    28
28    28
25    28
23    28
49    28
54    28
53    28
22    28
21    28
26    28
31    27
41    27
44    27
43    27
42    27
29    27
30    27
40    27
32    26
33    26
57    26
34    26
55    26
56    26
35    25
58    25
37    25
59    25
39    25
36    25
38    25
62    23
60    23
63    23
61    23
64    22
Name: count, dtype: int64

In [137]:
df["bmi"].value_counts()

bmi
32.300    13
28.310     9
30.800     8
31.350     8
30.495     8
          ..
20.350     1
31.240     1
19.095     1
22.100     1
21.280     1
Name: count, Length: 548, dtype: int64

In [138]:
df["charges"].value_counts()

charges
1639.56310     2
6203.90175     1
12981.34570    1
28101.33305    1
28923.13692    1
              ..
1163.46270     1
19496.71917    1
7201.70085     1
5425.02335     1
16115.30450    1
Name: count, Length: 1337, dtype: int64

In [139]:
df["children"].value_counts()

children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

In [140]:
df.dtypes#datatypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [141]:
df.shape#rows&columns

(1338, 7)

In [142]:
numerical_cols=df.select_dtypes(include=['int64','float64'])
print(numerical_cols)#nnumerical features

      age     bmi  children      charges
0      19  27.900         0  16884.92400
1      18  33.770         1   1725.55230
2      28  33.000         3   4449.46200
3      33  22.705         0  21984.47061
4      32  28.880         0   3866.85520
...   ...     ...       ...          ...
1333   50  30.970         3  10600.54830
1334   18  31.920         0   2205.98080
1335   18  36.850         0   1629.83350
1336   21  25.800         0   2007.94500
1337   61  29.070         0  29141.36030

[1338 rows x 4 columns]

In [143]:
categorical_cols=df.select_dtypes(include='object')
print(categorical_cols)#categorical features

         sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1338 rows x 3 columns]

In [144]:
print(df.columns)#features name

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [145]:
print(df['charges'])#target variable

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [146]:
a=pd.get_dummies(df['sex'],dtype=int)#encode

In [147]:
b=pd.get_dummies(df['smoker'],dtype=int)

In [148]:
c=pd.get_dummies(df['region'],dtype=int)

In [149]:
df['smoker'].map({'yes':1,'no':0})

0       1
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    1
Name: smoker, Length: 1338, dtype: int64

In [150]:
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

In [151]:
categorical_cols=df.select_dtypes(include='object')
print(categorical_cols)#categorical features

         sex smoker     region
0     female    yes  southwest
1       male     no  southeast
2       male     no  southeast
3       male     no  northwest
4       male     no  northwest
...      ...    ...        ...
1333    male     no  northwest
1334  female     no  northeast
1335  female     no  southeast
1336  female     no  southwest
1337  female    yes  northwest

[1338 rows x 3 columns]

In [152]:
#drop the originl categorical column
df_numeric=df.drop(columns=['region','smoker','sex'])

In [153]:
df_final=pd.concat([df_numeric,a,b,c],axis=1)#contact the encoded data

In [154]:
all_numerical_cols=df_final.select_dtypes(include=['int64','float64'])#verifying the numerical encoding
print(all_numerical_cols)

      age     bmi  children      charges  female  male  no  yes  northeast  \
0      19  27.900         0  16884.92400       1     0   0    1          0
1      18  33.770         1   1725.55230       0     1   1    0          0
2      28  33.000         3   4449.46200       0     1   1    0          0
3      33  22.705         0  21984.47061       0     1   1    0          0
4      32  28.880         0   3866.85520       0     1   1    0          0
...   ...     ...       ...          ...     ...   ...  ..  ...        ...
1333   50  30.970         3  10600.54830       0     1   1    0          0
1334   18  31.920         0   2205.98080       1     0   1    0          1
1335   18  36.850         0   1629.83350       1     0   1    0          0
1336   21  25.800         0   2007.94500       1     0   1    0          0
1337   61  29.070         0  29141.36030       1     0   0    1          0

      northwest  southeast  southwest
0             0          0          1
1             0          1          0
2             0          1          0
3             1          0          0
4             1          0          0
...         ...        ...        ...
1333          1          0          0
1334          0          0          0
1335          0          1          0
1336          0          0          1
1337          1          0          0

[1338 rows x 12 columns]

In [ ]:
numerical__featurews_cols=[]